# Generated by Django 4.1.5 on 2023-01-13 23:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='starred_by',
            field=models.ManyToManyField(related_name='starred_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
