# Generated by Django 4.1.5 on 2023-01-14 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cram', '0002_collection_starred_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='success',
            new_name='success_rate',
        ),
        migrations.AlterField(
            model_name='card',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cram_cards', to='cram.collection'),
        ),
        migrations.AlterField(
            model_name='usercardscore',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cram_scores', to='cram.card'),
        ),
        migrations.AlterField(
            model_name='usercardscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cram_scores', to=settings.AUTH_USER_MODEL),
        ),
    ]
