# Generated by Django 4.1.5 on 2023-01-14 05:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cram', '0004_alter_collection_starred_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['concept']},
        ),
        migrations.AddField(
            model_name='card',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
