# Generated by Django 4.1.5 on 2023-01-18 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cram', '0006_remove_card_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
