# Generated by Django 4.1.4 on 2023-01-03 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hold', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='estimated_wealth',
            field=models.FloatField(default=14600000000.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
