# Generated by Django 4.1.4 on 2023-01-03 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hold', '0002_entity_estimated_wealth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='estimated_wealth',
            field=models.BigIntegerField(default=14600000000.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
