# Generated by Django 4.1.4 on 2023-01-03 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hold', '0003_alter_entity_estimated_wealth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='estimated_wealth',
        ),
        migrations.AddField(
            model_name='entity',
            name='wealth',
            field=models.BigIntegerField(default=14600000000.0, help_text='Million EUR', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
