# Generated by Django 4.1.4 on 2023-01-05 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hold', '0004_remove_entity_estimated_wealth_entity_wealth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='wealth',
            field=models.BigIntegerField(default=14.6, help_text='Billion EUR', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
